version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  oncall-web-2:
    build: .
    hostname: oncall2
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  balancer:
    build: ./balancer
    ports:
      - "8080:80"
    volumes:
      - ./balancer/configs/:/etc/nginx/conf.d/
    networks:
      - iris  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://balancer:80/stub_status"
    networks:
      - iris
    depends_on:
     - balancer
networks:
  iris:
    name: iris
