scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerized-services'
    scrape_interval: 1m
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: "publish"
            values: ["9999"]
