scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'external-node'
    scrape_interval: 1m
    static_configs:
      - targets: ['158.160.96.191:9600']

  - job_name: 'my-dockerized-services'
    scrape_interval: 1m
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: "publish"
            values: ["9999"]
