services:
  oncall-exporter:
    build: .
    environment:
      - EXPORTER_LOG_LEVEL=info
      - EXPORTER_METRICS_PORT=9447
      - EXPORTER_UPDATE_INTERVAL=60
      - ONCALL_HOST=http://158.160.96.191:8080/
    ports:
      - "9227:9227"